# Generated by Django 5.0.6 on 2024-07-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playing_card_container', models.CharField(max_length=100)),
                ('card_done', models.CharField(max_length=100)),
                ('group_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.users')),
            ],
        ),
    ]
