# Generated by Django 5.0.6 on 2024-07-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cardcontainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='created',
        ),
        migrations.AddField(
            model_name='cardcontainer',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='game_starting_player',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='start_distribution',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardcontainer',
            name='card_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cardcontainer',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
